### PR TITLE
Updated Twitter video async upload (comment off some code and keep the comment string)

### PR DESCRIPTION
**Pull request by malonguwa**
I have comment off some unnecessary error checking codes and keep the old comment string content :)

### CODE REVIEW

**Comment by malonguwa** [comment]
@liu044100 Hi mate, I haven't see any of your comment under this new PR? am I looking at the wrong place?

**Comment by liu044100** [comment]
@malonguwa https://github.com/liu044100/SocialVideoHelper/pull/9/files#diff-24ad1455862541f5420477729b46af82R222

**Comment by malonguwa** [comment]
@liu044100 Thanks for your reply~ I have a look the part of code that your link jump to, But i'm still confused, I am sorry for that, Could you tell me Is there anything wrong about the code? and I do not see any line comment with the code? Thanks for the help~ :)

**Comment by liu044100** [comment]
@malonguwa Sorry for my bad explanation, I think the code from line numbers 225 ~242 can be deleted, because it is unnecessary now.

**Comment by malonguwa** [comment]
@liu044100 Thanks for the reply, I believe the line 225 - 242 is necessary code, if you comment off the code, the upload is incomplete, I just try to upload a small video to Twitter with line 225 - 242 commented off, there is no error or any data coming back from the Twitter server, the uploading seems stopped, and never finish the uploading.
Once I keep line 225 - 242, everything works nice :) Thanks ~

**Comment by liu044100** [comment]
@malonguwa Sorry, I misunderstand it. I will merge it.

**Pull request merged**
